! This file was automatically generated by SWIG (https://www.swig.org).
! Version 4.2.0+fortran
!
! Do not make changes to this file unless you know what you are doing - modify
! the SWIG interface file instead.
module f90cbf
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type
 public :: cbf_array2minicbf

! WRAPPER DECLARATIONS
interface
function swigc_cbf_array2minicbf(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8) &
bind(C, name="_wrap_cbf_array2minicbf") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(C_PTR), intent(in) :: farg2
type(SwigArrayWrapper) :: farg3
type(SwigArrayWrapper) :: farg4
integer(C_SIZE_T), intent(in) :: farg5
integer(C_SIZE_T), intent(in) :: farg6
integer(C_SIZE_T), intent(in) :: farg7
integer(C_SIZE_T), intent(in) :: farg8
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS

subroutine SWIGTM_fin_char_Sm_(finp, iminp, temp)
  use, intrinsic :: ISO_C_BINDING
  character(len=*), intent(in) :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  character(kind=C_CHAR), dimension(:), target, allocatable, intent(out) :: temp
  integer :: i

  allocate(character(kind=C_CHAR) :: temp(len(finp) + 1))
  do i=1,len(finp)
    temp(i) = char(ichar(finp(i:i)), kind=C_CHAR)
  end do
  i = len(finp) + 1
  temp(i) = C_NULL_CHAR ! C finp compatibility
  iminp%data = c_loc(temp)
  iminp%size = len(finp, kind=C_SIZE_T)
end subroutine

function cbf_array2minicbf(filename, array, header, compression, dimfast, dimmid, dimslow, elsize) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
character(len=*), target :: filename
type(C_PTR), intent(in) :: array
character(len=*), target :: header
character(len=*), target :: compression
integer(C_SIZE_T), intent(in) :: dimfast
integer(C_SIZE_T), intent(in) :: dimmid
integer(C_SIZE_T), intent(in) :: dimslow
integer(C_SIZE_T), intent(in) :: elsize
integer(C_INT) :: fresult 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 
type(C_PTR) :: farg2 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg3_temp 
type(SwigArrayWrapper) :: farg3 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg4_temp 
type(SwigArrayWrapper) :: farg4 
integer(C_SIZE_T) :: farg5 
integer(C_SIZE_T) :: farg6 
integer(C_SIZE_T) :: farg7 
integer(C_SIZE_T) :: farg8 

call SWIGTM_fin_char_Sm_(filename, farg1, farg1_temp)
farg2 = array
call SWIGTM_fin_char_Sm_(header, farg3, farg3_temp)
call SWIGTM_fin_char_Sm_(compression, farg4, farg4_temp)
farg5 = dimfast
farg6 = dimmid
farg7 = dimslow
farg8 = elsize
fresult = swigc_cbf_array2minicbf(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8)
swig_result = fresult
end function


end module
